import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbarcenter from '@/components/navbar'
import Footerbasiclarge from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div><Navbarcenter/></div>
        <div className='min-h-[90vh]'>{children}</div>
        <div><Footerbasiclarge/></div>
      </body>
    </html>
  );
}
